### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by jimlynnjulian** [waxlamp/nightshade#19]
Using the Pypi pip install version in Windows 11 x64 Pro , MS-DOS CLI..

C:\Users\jimly\Downloads\Rotten Tomatoes scrapers\nightshade-0.1.0.tar\nightshade-0.1.0>nightshade search -s "https://www.rottentomatoes.com/m/matrix"
No output.

C:\Users\jimly\Downloads\Rotten Tomatoes scrapers\nightshade-0.1.0.tar\nightshade-0.1.0>nightshade search -s "Matrix"
No output.

C:\Users\jimly\Downloads\Rotten Tomatoes scrapers\nightshade-0.1.0.tar\nightshade-0.1.0>nightshade search -s "Matrix" -y "1999"
No output.

**Comment by waxlamp** [comment]
Unfortunately, RT changes their webpage structure often, and this tool requires updates to its parser in order to keep up. If you feel like updating the code until it works again, I'm glad to accept a PR. Otherwise, I will get to it eventually myself, but it may be a while as life is getting in the way.

Since this will be a continuing problem for this software, I'm going to close the issue, but please don't take that as my dismissing the bug report -- it's just that it's an expected failure for this mode of web scraping.

**Comment by jimlynnjulian** [comment]
Thanks for the notice.
